def koncate(letter, x, y ):  return letter+str(x+y)
list=str(input('Write the string: '))
n1=int(input('Write the first number:'))
n2=int(input('Write the second number:'))
print(koncate(list, n1, n2))